apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apinetlet-system
  name: apinetlet-controller-manager
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
